name: Deploy Angular App to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH and Deploy on Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short commit ID
        id: vars
        run: echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Connect via SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "ğŸ”§ DÃ©ploiement avec le commit ID : ${{ steps.vars.outputs.commit_id }}"

            # Aller dans le dossier de l'app
            cd  Idem-app/

            # Tag de l'image avec commit ID
            export COMMIT_ID=${{ steps.vars.outputs.commit_id }}
            export IMAGE_NAME=ghcr.io/${{ github.repository }}/idem-frontend:$COMMIT_ID

            echo "ğŸ”„ Construction de lâ€™image avec les variables locales..."
            docker build -t $IMAGE_NAME .

            echo "ğŸ“¤ Push de lâ€™image vers le GitHub Container Registry..."
            docker push $IMAGE_NAME

            echo "ğŸ” Mise Ã  jour du docker-compose..."
            sed -i "s|image: ghcr.io/.*/idem-frontend:.*|image: $IMAGE_NAME|" docker-compose.yml

            echo "ğŸš€ Restart docker-compose..."
            docker-compose down && docker-compose up -d
