name: CI/CD IDEM FRONTEND

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: üîß Build Docker image on remote server
    runs-on: ubuntu-latest
    outputs:
      commit_id: ${{ steps.vars.outputs.commit_id }}
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short commit ID
        id: vars
        run: echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: SSH Build Image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Idem-app/idem
            BRANCH=${{ github.ref_name }}
            git checkout dev
            git pull origin dev

            export COMMIT_ID=${{ steps.vars.outputs.commit_id }}
            export IMAGE_NAME=ghcr.io/idem-ia/idem:$COMMIT_ID

            echo "üî® Build Docker image $IMAGE_NAME"
            docker build -t $IMAGE_NAME .

  push:
    name: üì§ Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    steps:
      - name: SSH Push Image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Idem-app/idem
            export IMAGE_NAME=ghcr.io/idem-ia/idem:${{ needs.build.outputs.commit_id }}

            echo "üì§ Push Docker image $IMAGE_NAME"
            docker push $IMAGE_NAME

  deploy:
    name: üöÄ Deploy with docker-compose
    runs-on: ubuntu-latest
    needs: push
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Idem-app/idem

            export COMMIT_ID=${{ needs.push.needs.build.outputs.commit_id }}
            export IMAGE_NAME=ghcr.io/idem-ia/idem:$COMMIT_ID

            if [ "${{ github.ref_name }}" = "main" ]; then
              COMPOSE_FILE=docker-compose.yml
            else
              COMPOSE_FILE=docker-compose.staging.yml
            fi

            echo "üîÅ Mise √† jour de l'image dans $COMPOSE_FILE"
            sed -i "s|image: ghcr.io/.*/idem:.*|image: $IMAGE_NAME|" $COMPOSE_FILE

            echo "‚ôªÔ∏è Restarting docker-compose using $COMPOSE_FILE"
            docker-compose -f $COMPOSE_FILE up -d idem
